import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";

const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const definitions = app.split("els.cloud.addEventListener")[0];
const dummy = () => ({
  className:"",textContent:"",innerHTML:"",hidden:false,disabled:false,dataset:{},style:{width:"",setProperty(){}},
  classList:{add(){},remove(){},toggle(){}},setAttribute(){},querySelector(){return dummy()},close(){},showModal(){},animate(){},
});
const storage = new Map();
const context = {
  console,Date,Math,Number,Object,Array,String,RegExp,JSON,Intl,setTimeout,clearTimeout,
  localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},
  document:{querySelector:dummy,querySelectorAll:()=>[],body:dummy(),createElement:dummy},
  window:{},innerWidth:1200,innerHeight:800,fetch:async()=>{throw new Error("offline test")}
};

const checks = `
assert.equal(units.length,24,"Le jeu doit contenir 24 automates");
assert.equal(MILESTONES.length,16,"Chaque automate doit avoir 16 paliers");
assert.equal(globalUpgrades.length,20,"Le jeu doit proposer 20 innovations globales");
const ids=units.flatMap(unit=>MILESTONES.map((_,index)=>unitUpgradeId(unit,index)));
assert.equal(new Set(ids).size,384,"Les 384 identifiants de paliers doivent être uniques");
state=initialState();state.buyMode="max";state.drops=0;
const unavailableFan=purchaseQuote(units[0]);
assert.equal(unavailableFan.count,0,"Le mode Max doit indiquer qu’aucun automate n’est encore achetable");
assert.equal(unavailableFan.cost,unitCost(units[0],1),"Le mode Max doit conserver le prix du prochain automate");
renderUnits();
assert.match(els.units.innerHTML,/Pas encore abordable/,"Un automate non achetable ne doit pas être présenté comme limité");
assert.doesNotMatch(els.units.innerHTML,/Limite atteinte/,"Le jeu ne doit pas afficher de fausse limite d’achat");
state=initialState();state.owned.fan=10;
assert.equal(baseProduction(),2,"Dix ventilateurs doivent produire 2 gouttes/s avant bonus");
state.upgrades.push(unitUpgradeId(units[0],0),unitUpgradeId(units[0],1),unitUpgradeId(units[0],2));
assert.equal(unitMultiplier(units[0]),8,"Les trois premiers paliers doivent cumuler trois multiplicateurs ×2");
state.runTotal=1e9;state.drops=1e9;state.lifetime=1e9;state.pendingPath="storm";initialized=true;
state.buyMode="max";
assert.equal(canPrestige(),true,"La première Aube doit être disponible à 1 milliard");
prestige();
assert.equal(state.cycles,1,"Le prestige doit accorder exactement une Aube");
assert.equal(state.dawns,1,"Le prestige doit créditer une Aube dépensable");
assert.equal(state.currentPath,"storm","Le cycle doit commencer dans la voie choisie");
assert.equal(state.buyMode,"max","Le mode d’achat doit être conservé après un cycle");
assert.equal(permanentMultiplier(),1.35,"Un cycle doit apporter le bonus permanent de 35 %");
state.dawnUpgrades.push("born_ready");
assert.equal(starterGrant(),5e6,"Né prêt doit offrir 5 M gouttes sur Terre");
state.dawnUpgrades=[];
buyDawn("first_light");
assert.equal(dawnBalance(),0,"L’Aube achetée doit quitter le solde disponible");
assert.equal(permanentMultiplier(),1.6875,"La Première lueur doit s’ajouter au bonus de cycle");
assert.equal(state.runTotal,0,"Le total de l’ère doit repartir à zéro");
assert.equal(state.owned.fan,0,"Les automates doivent être perdus au prestige");
assert.equal(state.lifetime,1e9,"Le total historique doit être conservé");
state.stats.contractsCompleted=160;
assert.equal(contractTarget(contractTemplates[0]),500,"Les contrats de condensation doivent plafonner à 500 clics");
assert.equal(contractDuration(contractTemplates[0],500),100,"500 clics doivent laisser 100 secondes");
assert.equal(contractDuration(contractTemplates[1],1e30),90,"Les contrats de réserve doivent conserver leur durée normale");
state.stats.contractsCompleted=0;
state.contract={id:"clicks",target:2,progress:0,startedAt:0,expiresAt:Date.now()+60000};
recordContractProgress("clicks",1);recordContractProgress("clicks",1);
assert.equal(state.stats.contractsCompleted,1,"Un contrat doit être validé lorsque sa cible est atteinte");
state.activeEvent={id:"golden",spawnedAt:0,expiresAt:Date.now()+60000,boostUntil:0};
claimEvent();
assert.equal(state.stats.eventsCaptured,1,"Un phénomène rare doit pouvoir être capturé");
assert.equal(state.activeEvent,null,"Un événement instantané doit disparaître après capture");
state.dawns=3;state.dawnSpent=0;state.dawnUpgrades=[];
assert.equal(canBuyDawn(dawnNode("dawnflare")),false,"Le phénomène d’Aube doit coûter quatre Aubes");
assert.equal(unlockedRareEvents().some(event=>event.id==="dawnflare"),false,"Le phénomène d’Aube doit rester verrouillé avant son achat");
state.dawns=4;buyDawn("dawnflare");
assert.equal(hasDawn("dawnflare"),true,"Quatre Aubes doivent permettre d’acheter l’Éclair d’aube");
assert.equal(unlockedRareEvents().some(event=>event.id==="dawnflare"),true,"Le phénomène d’Aube doit se débloquer après son achat");
state.activeEvent={id:"dawnflare",spawnedAt:0,expiresAt:Date.now()+60000,boostUntil:Date.now()+7000};
assert.equal(eventMultiplier("production"),100000,"L’Éclair d’aube doit offrir ×100 000 pendant son activation");
assert.equal(displayRareEvent(rareEvents.find(event=>event.id==="dawnflare")).name,"Éclair d’aube","La Terre doit afficher son propre phénomène majeur");
state.pathUpgrades.push("path_storm_spark");
assert.equal(rainPower(),4,"La voie des orages doit renforcer les averses");
assert.equal(pathTechList().length,8,"Chaque voie doit proposer huit recherches exclusives");
state.drops=1e20;
buyProject("project_storm_coil");
assert.equal(state.relics.storm,1,"Un projet doit créer une relique persistante");
assert.equal(relicMultiplier(),1.1,"Une relique doit renforcer définitivement la production");
state.owned.fan=1;state.runTotal=1000;state.drops=160;state.upgrades=[];state.stats.upgradesBought=0;
renderUpgrades();
assert.equal(els.buyAllUpgrades.hidden,true,"L’achat groupé doit rester caché avant deux Aubes");
state.cycles=2;renderUpgrades();
assert.equal(els.buyAllUpgrades.hidden,false,"L’achat groupé doit apparaître après deux Aubes");
assert.equal(els.buyAllUpgrades.disabled,false,"Le bouton d’achat groupé doit s’activer lorsqu’une innovation est accessible");
buyAllAvailableUpgrades();
assert.equal(hasUpgrade("soft_gloves"),true,"L’achat groupé doit prendre l’innovation la moins chère en premier");
assert.equal(hasUpgrade("unit_fan_0"),false,"L’achat groupé doit s’arrêter lorsque le budget ne suffit plus au protocole suivant");
state.drops+=100;buyAllAvailableUpgrades();
assert.equal(hasUpgrade("unit_fan_0"),true,"L’achat groupé doit pouvoir reprendre les protocoles restants");
state.expedition=[];state.lifetime=100;updateExpedition();
assert.equal(state.expedition[0],"first_drop","L’expédition doit valider ses jalons dans l’ordre");
state.expedition=expeditionChapters.slice(0,7).map(chapter=>chapter.id);state.owned.fan=100;state.activeBoss=null;
startBoss();
assert.equal(state.activeBoss.id,"storm_boss","La première tempête-boss doit pouvoir démarrer");
recordBossAction("clicks",25);
recordBossProgress(state.activeBoss.target);
assert.equal(state.expedition.includes("storm_boss"),true,"Une tempête-boss doit valider son jalon à l’objectif");
state.upgrades.push("storm_bottle","eternal_rain");state.pathUpgrades.push("path_storm_wetwire");
assert.equal(rainDuration(),72,"Les améliorations de durée doivent pouvoir allonger une averse à 72 secondes");
assert.equal(bossActionTarget("rain"),2,"Un boss terrestre ne doit pas demander trois averses de 72 secondes en 90 secondes");
state.expedition=expeditionChapters.slice(0,9).map(chapter=>chapter.id);state.activeBoss=null;
startBoss();
assert.equal(state.activeBoss.actionTarget,2,"Le boss terrestre doit conserver l’objectif d’averse réalisable calculé au lancement");
state.stats.clicks=100;updateAchievements();
assert.equal(state.unlockedAchievements.includes("clicker"),true,"Les succès doivent être débloqués automatiquement");
state.expedition=expeditionChapters.map(chapter=>chapter.id);state.drops=finalCost();
assert.equal(canBuildFinal(),false,"La fin terrestre doit demander une Constellation développée");
state.cycles=3;state.dawnUpgrades=["first_light","swift_touch","deep_sleep"];
assert.equal(canBuildFinal(),true,"Trois Aubes et trois héritages doivent préparer la conclusion terrestre");
state.finalBuilt=true;state.newGamePlus=0;beginNewGamePlus();
assert.equal(state.planet,"mars","La conclusion terrestre doit révéler Mars");
assert.equal(units.length,30,"Mars doit contenir 30 nouveaux automates");
assert.equal(MILESTONES.length,20,"Les automates martiens doivent avoir une progression plus longue");
assert.equal(expeditionChapters.length,15,"La conquête martienne doit proposer quinze jalons");
state.dawns=4;state.dawnSpent=0;state.dawnUpgrades=[];buyDawn("dawnflare");
assert.equal(unlockedRareEvents().some(event=>event.id==="dawnflare"),true,"Quatre Sols doivent déverrouiller l’éruption martienne");
assert.equal(displayRareEvent(rareEvents.find(event=>event.id==="dawnflare")).name,"Éruption d’Olympus","Mars doit afficher son propre phénomène majeur");
state.dawnUpgrades=["born_ready"];
assert.equal(starterGrant(),5e9,"Colonie équipée doit offrir 5 Md grains sur Mars");
state.dawnUpgrades=[];
assert.equal(unitMilestonePower(units[0],11),1,"Le cap normal des pionniers doit laisser place à leur résonance spéciale");
const pioneerSuper=pioneerSuperUpgrade(units[0],500);
assert.equal(pioneerSuper.description.includes("7.78 M"),true,"Le 500e pionnier doit proposer une résonance ×7 777 777");
state.owned.dust_scoop=1000;state.upgrades.push(pioneerSuperUpgradeId(units[0],500),pioneerSuperUpgradeId(units[0],1000));
assert.equal(unitMultiplier(units[0])>=PIONEER_SUPER_POWER**2,true,"Chaque tranche de 500 pionniers doit cumuler une nouvelle résonance");
assert.equal(format(1e63).includes("Vg"),true,"Les ressources au-delà de 1e62 doivent garder une unité lisible");
state.owned.dust_scoop=0;state.upgrades=[];
assert.equal(unitMilestonePower(units[28],0),1000,"Les automates colossaux doivent commencer par un palier ×1000");
const colossus=units.find(unit=>unit.id==="ares_colossus"),firstColossusCost=unitCost(colossus,1,0),postCapColossusCost=unitCost(colossus,1,1);
assert.equal(postCapColossusCost/firstColossusCost>COLOSSUS_CAP_TAX,true,"Chaque cap de Colosse doit rendre l’achat suivant très coûteux");
state.buyMode="1";state.drops=20;buyUnit("dust_scoop");
assert.equal(state.marsUnitsBuilt,1,"Les machines martiennes déployées doivent être comptées séparément");
state.marsUnitsBuilt=99999;
assert.equal(marsExpeditionChapters.find(chapter=>chapter.id==="mars_colony").check(state),false,"Le jalon colonial doit attendre 100 000 machines martiennes cumulées");
state.marsUnitsBuilt=100000;
assert.equal(marsExpeditionChapters.find(chapter=>chapter.id==="mars_colony").check(state),true,"Le jalon colonial doit accepter les machines martiennes cumulées entre les Sols");
state.currentPath="storm";state.upgrades.push("storm_bottle","eternal_rain");state.pathUpgrades.push("path_storm_wetwire");
assert.equal(rainDuration(),72,"Mars doit utiliser les mêmes durées d’averse longues");
assert.equal(bossActionTarget("rain"),2,"Un boss martien ne doit pas demander trois surcharges de 72 secondes en 90 secondes");
state.expedition=marsExpeditionChapters.slice(0,9).map(chapter=>chapter.id);state.activeBoss=null;
startBoss();
assert.equal(state.activeBoss.actionTarget,2,"Le boss martien doit appliquer le même plafond d’objectif réalisable");
state.activeBoss.actionTarget=3;state.economyVersion=2;rebalanceLegacyEconomy();
assert.equal(state.activeBoss.actionTarget,2,"Une tentative de boss déjà ouverte doit être corrigée au chargement");
state.cycles=1;renderUpgrades();
assert.equal(els.buyAllUpgrades.hidden,true,"L’automatisation doit aussi attendre deux Sols sur Mars");
state.cycles=2;renderUpgrades();
assert.equal(els.buyAllUpgrades.hidden,false,"L’automatisation doit apparaître après deux Sols sur Mars");
state.owned.dust_scoop=500;state.owned.mars_heart=1;clockOffset=-Date.now()+1000;
assert.equal(marsResonancePhase(),0,"Le test doit placer Mars dans l’Écho des pionniers");
assert.equal(marsResonanceMultiplier(units[0])>marsResonanceMultiplier(units[29]),true,"La résonance doit pouvoir rendre le premier automate dominant");
const strongestRaw=rawUnitProduction(units[29]),pioneerRaw=rawUnitProduction(units[0]);
const resonantPioneer=pioneerRaw*marsResonanceMultiplier(units[0]);
assert.equal(resonantPioneer>=strongestRaw*1.5&&resonantPioneer<=strongestRaw*2,true,"Un ancien automate résonant doit dépasser le meilleur automate sans emballement");
assert.equal(baseProduction()/stableProduction()<4,true,"La résonance d’un pionnier ne doit plus faire exploser toute l’économie");
state.owned.solar_tick=1;state.owned.crawler=1;state.owned.ice_drill=1;state.owned.oxygen_moss=1;
assert.equal(baseProduction()/stableProduction()<5,true,"La résonance doit partager son énergie entre les automates actifs d’un même groupe");
state.stats.contractsCompleted=0;
assert.equal(contractTarget(contractTemplates[1]),stableProduction()*35,"La cible d’un contrat doit ignorer la résonance");
assert.equal(contractReward(),stableProduction()*60,"La récompense d’un contrat doit ignorer la résonance");
state.contract={id:"drops",target:baseProduction()*35,progress:baseProduction()*7,startedAt:0,expiresAt:Date.now()+60000};state.economyVersion=1;
rebalanceLegacyEconomy();
assert.equal(state.contract.target,stableProduction()*35,"Un ancien contrat martien doit être recalculé sans résonance");
assert.equal(Math.round(state.contract.progress/state.contract.target*100),20,"La migration doit conserver l’avancement relatif du contrat");
clockOffset=0;
assert.equal(finalCost(),1e86,"La fin martienne doit coûter 100 Spvg");
state.expedition=marsExpeditionChapters.map(chapter=>chapter.id);state.drops=finalCost();state.cycles=3;state.dawnUpgrades=["first_light","swift_touch","deep_sleep"];
assert.equal(canBuildFinal(),false,"La fin martienne doit demander une Constellation plus développée");
state.cycles=4;state.dawnUpgrades.push("storm_soul");
assert.equal(canBuildFinal(),true,"Quatre Sols et quatre héritages doivent préparer la conclusion martienne");
state.finalBuilt=true;beginNewGamePlus();
assert.equal(state.planet,"venus","La conclusion martienne doit révéler Vénus");
assert.equal(units.length,32,"Vénus doit proposer 32 nouvelles machines flottantes");
assert.equal(MILESTONES.length,20,"Les machines vénusiennes doivent avoir vingt paliers");
assert.equal(expeditionChapters.length,16,"L’Ascension de Vénus doit contenir seize jalons");
state.dawnUpgrades=["born_ready"];
assert.equal(starterGrant(),5e12,"Une Élévation équipée doit commencer avec 5 Bn lumens");
state.dawnUpgrades=[];state.venusCorrosion=0;toggleVenusOverdrive();
assert.equal(venusOverdriveMultiplier(),25,"La surcadence vénusienne doit multiplier la production par 25");
assert.equal(state.stats.overdrives,1,"Chaque activation de surcadence doit être recensée");
state.venusCorrosion=99;updateVenusSystems(1);
assert.equal(state.venusOverdrive,false,"Une corrosion critique doit couper la surcadence");
state.venusCooldownUntil=0;state.venusCorrosion=0;state.drops=venusMegaprojects[0].cost;startVenusConstruction("ishtar_haven");
assert.equal(state.venusBuild.id,"ishtar_haven","Le Havre d’Ishtar doit lancer un chantier persistant");
state.venusBuild.completesAt=now();finishVenusConstruction();
assert.equal(state.venusConstructions.includes("ishtar_haven"),true,"Un chantier terminé doit rester inscrit dans Vénus");
assert.equal(venusConstructionEffect("all",1),3,"Le Havre d’Ishtar doit tripler la production");
assert.equal(finalCost(),1e140,"Le Trône du Crépuscule doit constituer une véritable fin vénusienne");
state.expedition=venusExpeditionChapters.map(chapter=>chapter.id);state.drops=finalCost();state.cycles=5;state.dawnUpgrades=["first_light","swift_touch","deep_sleep","storm_soul","lean_air"];
assert.equal(canBuildFinal(),true,"Cinq Élévations et cinq héritages doivent préparer la fin de Vénus");
state.finalBuilt=true;beginNewGamePlus();
assert.equal(state.newGamePlus,1,"Nouvelle Vénus+ doit augmenter le niveau permanent");
assert.equal(newGamePlusMultiplier(),1.5,"Nouvelle Météo+ doit accélérer la progression suivante");
`;

vm.runInNewContext(`${definitions}\n${checks}`, {...context,assert});
console.log("✓ Économie, paliers et prestige validés");
